seq = """TATAGAAAATCGTATCGAAACTTTCCTTAAGACTGTCAAACCGATGGGATGTCAAAACGCCACGGTCGAGGACGAGGCATGTCTCTATCTATGATGATGGGACGTGTGTATCTCTTACATATGATCCAAGAATAGCAGAGTATGAAGTATTTTAGCTAGTCCAACTTCAGTGCACTCGATCGCCATTACATCCTGGGCAGGTACATGCAGCACGCTTCCTCTCGGCCCCAATCGCTAACACAGTCCTTTGCATAGTCTCACTGAATGGTCGATGATGTGGTTGACCTACTGGCACTTTGGGCCTGCATTGTAACTATACGGAGCAAGGAAGTCAAAGCGTCGTGGATACCGTAGGCAGTTACGTACTAATGGCGTCCATCTGACCCGCTCTCCGCTCTAGCAGTATATCAGTAGGTTGATCAAGAATCGATCCAGTGTGTCAACACGTGTTGCGGTCCGTGGCCTCAATCCTATGCTCCCTGTCAGTGCGTCGACAGGAGTCCTTTGTATCTACTTCACAAGTTATAAAACCGACGCTTATCCCCCCGGTTTCATCTCAAGGTACTGCGATCACGCACTATTATGCTTGGACGTTATCTCCCCATGTCCCCGTTCGCACGTGGCACGTCCTTCCCACGCGCAATAGACCCGTCCCCGCTACTTCCGAGAGTACAACTCAAGAGCCGGTAGCTAGCTCACAGGACCGCGAACCTAGGACCCACGCCCCGACAACCCCTAGAGCATGATCATTGGAGCCTATGGCCTCGGAAAGTTATGGGATGCCGGACTCGGTACCATATCAGCCGGACATATAGCTGCTTTTAATAGTCATACGCGACTAATAGAATACTATACCTTGGCCTGTAACTGCCTCGTCTGTTTGGTTCGTATA"""

compl = {'A':'T','G':'C','T':'A','C':'G'}

def revcompl(s):
    return ''.join([compl[c] for c in s[::-1]])

all = []

for j in range(4,12+1,2):
    for i in range(len(seq)-j+1):
        s = seq[i:i+j]
        if (s==revcompl(s)):
            all.append((i+1,len(s)))

all = sorted(all)

for e in all:
    print("{} {}".format(e[0],e[1]))
